// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPK3r68-nunYzGhu1K9nRUjRkw6f1zBmE',
    appId: '1:30745917348:web:ff2f4b3df9c5eb704ef331',
    messagingSenderId: '30745917348',
    projectId: 'poshpicks-389d4',
    authDomain: 'poshpicks-389d4.firebaseapp.com',
    databaseURL: 'https://poshpicks-389d4-default-rtdb.firebaseio.com',
    storageBucket: 'poshpicks-389d4.appspot.com',
    measurementId: 'G-YLJN3SWJYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI9nCjmetdSZ07sQFTKBq0Nldgj5iUSk8',
    appId: '1:30745917348:android:ffa6525c32549e614ef331',
    messagingSenderId: '30745917348',
    projectId: 'poshpicks-389d4',
    databaseURL: 'https://poshpicks-389d4-default-rtdb.firebaseio.com',
    storageBucket: 'poshpicks-389d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3aiomz6LJNDNNVGCrEmWnbvUoBuxBWzQ',
    appId: '1:30745917348:ios:b9c83bb957df85574ef331',
    messagingSenderId: '30745917348',
    projectId: 'poshpicks-389d4',
    databaseURL: 'https://poshpicks-389d4-default-rtdb.firebaseio.com',
    storageBucket: 'poshpicks-389d4.appspot.com',
    iosBundleId: 'com.example.poshpicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3aiomz6LJNDNNVGCrEmWnbvUoBuxBWzQ',
    appId: '1:30745917348:ios:bf1bb073861ef7a74ef331',
    messagingSenderId: '30745917348',
    projectId: 'poshpicks-389d4',
    databaseURL: 'https://poshpicks-389d4-default-rtdb.firebaseio.com',
    storageBucket: 'poshpicks-389d4.appspot.com',
    iosBundleId: 'com.example.poshpicks.RunnerTests',
  );
}
